### ISSUE TITLE
Text is out of bounds

### ISSUE THREAD

**Issue by ghost** [cryptpad/blueprints#13]
See on https://blueprints.cryptpad.org/prototypes/revocation/

<img width="679" alt="Screenshot 2024-05-02 at 11 17 44" src="https://github.com/cryptpad/blueprints/assets/156299270/ad7644da-27de-491b-8081-9b5fa4dedcbb">

**Comment by davidbenque** [comment]
code block styles should be fixed like this? 

![image](https://github.com/cryptpad/blueprints/assets/11028490/096f7e5e-f1df-4a24-b620-938113b412cc)

could be a browser issue
