### ISSUE TITLE
Menu navigation items are weird on Safari

### ISSUE THREAD

**Issue by mathilde-cryptpad** [cryptpad/blueprints#14]
See the lack of space between the · and the text:

![IMG_4A5DDA1FA6A5-1](https://github.com/cryptpad/blueprints/assets/156299270/2a0e4799-1a07-4e64-894f-4de0172cdbf8)

**Comment by davidbenque** [comment]
@mathilde-cryptpad  can you specify which browser you are using I am not reproducing this  on Chromium of Firefox on Linux
